### ISSUE TITLE
 tokenizer = Tokenizer.from_file(str(tokenizer_path)) Exception: data did not match any variant of untagged enum PyNormalizerTypeWrapper at line 49 column 3

### ISSUE THREAD

**Issue by gfkdliucheng** [dleemiller/WordLlama#16]
tokenizer = Tokenizer.from_file(str(tokenizer_path))
Exception: data did not match any variant of untagged enum PyNormalizerTypeWrapper at line 49 column 3

**Comment by gfkdliucheng** [comment]
win 10

**Comment by dleemiller** [comment]
I believe that you're encountering an issue with the tokenizers library. Eg.
https://stackoverflow.com/questions/77027040/running-llama-2-on-mac-using-huggingface

What version of tokenizers are you using? I might need to require a newer version.
