### ISSUE TITLE
wl.embed, wl.cluster high RAM usage

### ISSUE THREAD

**Issue by chapmanjacobd** [dleemiller/WordLlama#17]
First of all, thanks for putting together this tool! I'm interested in lightweight, data-driven tools like this. It's been fun to play around with this over the past few days.

I've added wordllama as an optional dependency in my xklb CLI multi-tool. But one of the things that makes me hesitate to make it the default is the RAM usage.

Here are some performance benchmarks on ~50k sentences (with `--wordllama` it uses wl.cluster under the hood):

| command                                    | time          | Maximum resident set size |
|--------------------------------------------|---------------|---------------------------|
| lb clustersort --wordllama 'trunc_dim=256' | 600.0s~714.7s | 19G                       |
| lb clustersort --wordllama 'trunc_dim=128' | 136.7s~397.6s | 18G                       |
| lb clustersort --wordllama 'trunc_dim=64'  | 60.7s~69.1s   | 11G                       |
| lb clustersort (TF-IDF+kmeans)             | 102.9s~184.6s | 850M                      |
| lb regexsort (simple text pipeline)        | 4.6s~5.4s     | 126M                      |

Obviously, these different tools don't do _exactly_ the same thing--but the output is often similar ([unsorted.txt](https://github.com/user-attachments/files/17077366/unsorted.txt) [wl.txt](https://github.com/user-attachments/files/17077362/wl.txt) [cs.txt](https://github.com/user-attachments/files/17077365/cs.txt) [rs.txt](https://github.com/user-attachments/files/17077364/rs.txt)), although they do sort single words very differently (`/usr/share/dict/words` [words_wl128.txt](https://github.com/user-attachments/files/17077181/words_wl128.txt) [words_cs.txt](https://github.com/user-attachments/files/17077182/words_cs.txt) [words_rs.txt](https://github.com/user-attachments/files/17077180/words_rs.txt)). 

I'm not very familiar with NLP tools but would sparse matrix support make a difference in wordllama?

I also would like to express my interest in the upcoming semantic text splitting feature(s). Please let me know when that is available!

**Comment by dleemiller** [comment]
Thanks for testing and making an issue. I'll try and reproduce it on my side and then do some profiling to see what I can do.

**Comment by dleemiller** [comment]
I ran some tests and was able to reproduce your results. I also traced it to the `embed()` method, and realized it needed to have batch processing to help keep the memory from blowing up. I think it should also resolve the long times and I believe it will be faster than the TF-IDF + kmeans method.

You should be able to install `v0.2.7` with the fixes and let me know how it goes!

> I also would like to express my interest in the upcoming semantic text splitting feature(s). Please let me know when that is available!

Noted -- I'll start experimenting with it and see what works. I'll also need to determine how to evaluate the algorithm. 

I've added an issue here: https://github.com/dleemiller/WordLlama/issues/19

**Comment by chapmanjacobd** [comment]
Wow! Memory usage is much more reasonable and it runs quite a bit faster too

    cat 50k_sentences | lb cs --wordllama 'config=l3_supercat dim=64'   #  38.2s, 401M
    cat 50k_sentences | lb cs --wordllama 'config=l3_supercat dim=128'  #  82.5s, 447M
    cat 50k_sentences | lb cs --wordllama 'config=l3_supercat dim=256'  # 187.1s, 666M
    cat 50k_sentences | lb cs --wordllama 'config=l3_supercat dim=512'  # 376.2s, 1.1G

Thanks again! I've subscribed to #19 for updates on semantic text splitting

**Comment by dleemiller** [comment]
I made one more update in v0.2.8 that might help. I found a bug in my code that caused early stopping. I also improved the efficiency of the cython implementation. If it appears to take longer, it's going deeper into iterations. Also, with the default `n_init` parameter, it actually runs kmeans 10 times with different initializations (which is sometimes more beneficial than going into deeper iterations).

**Comment by chapmanjacobd** [comment]
hmm... RAM usage is still low but it is quite a bit slower now. 

`ndim=64` with `k=int(len(sentence_strings) ** 0.5), n_init=10, max_iterations=300` takes about 17x longer: 649.6s

**Comment by dleemiller** [comment]
Yes, if you bring down the max_iterations to 10, it should be about the same as before. The problem is that it is actually set for a very high convergence. Inertia scales with the size of the dataset, so the tolerance becomes smaller with respect to the total inertia and compounds to longer convergence times.

I would suggest scaling down the `max_iterations` to the very longest latency you would tolerate, and then increasing the tolerance from 1e-4 until you reach the average latency you would like. Then ensure that the results look ok. Time will also scale linearly with `n_iter` since it is just re-initializing and running the entire clustering again.

I'll think about parallelizing. It could be done somewhat easily since the results can be evaluated at the end. The main tradeoff is that it will retain the labels in memory for each run until it finishes, but that would be pretty negligable if they were kept as uint8.

**Comment by chapmanjacobd** [comment]
Thanks for your guidance. It is very helpful!

Regarding tolerance, wordllama already scales the data so I don't need to worry about differences in data scale for that parameter, right? I just need to find a static value that matches my latency preference and it should work similarly (as a default value) for large and small datasets?

related link: https://github.com/scikit-learn/scikit-learn/issues/22519

**Comment by dleemiller** [comment]
You don't have to worry about scaling, but the stopping criteria is based on inertia, which typically increases with more points. When I was testing with 50k points, the inertia was ~43k, so shifts of 1e-4 are not very meaningful, although it technically was continuing to improve cluster centers with more iterations.

You can check the inertia for different settings, and find the tradeoff between them. For 50k points, in my testing, I found that run to run, the initialization had more impact than allowing long convergence, suggesting kmeans does get stuck in local minima anyway. So longer convergence can only improve the clustering so much, and trying more initializations is likely more worthwhile.
