### ISSUE TITLE
A example of using WordLlama for a RAG pipeline

### ISSUE THREAD

**Issue by dinhanhx** [dleemiller/WordLlama#25]
https://github.com/dinhanhx/cpu-ish-rag 

I recently implement a RAG pipeline with WordLlama, FAISS, gpt-4o-mini. You can copy my code for your own example as you wanted in your roadmap.

**Comment by SSobol77** [comment]
Hello,
Thank you for information.
Do you have a script for FreeBSD without Linux emulation?
Regards,
Siergej Sobolewski

Wysłano z programu Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________
From: dinhanhx ***@***.***>
Sent: Wednesday, September 25, 2024 10:14:50 AM
To: dleemiller/WordLlama ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dleemiller/WordLlama] A example of using WordLlama for a RAG pipeline (Issue #25)


https://github.com/dinhanhx/cpu-ish-rag

I recently implement a RAG pipeline with WordLlama, FAISS, gpt-4o-mini. You can copy my code for your own example as you wanted in your roadmap.

**Comment by dinhanhx** [comment]
@SSobol77 sorry sir, I think you mistake me with someone else. I don't do anything with FreeBSD

**Comment by dleemiller** [comment]
This is cool! Thanks for sharing. I'll add it to the community projects.
