### ISSUE TITLE
Nice work. (stupid question) Can you pass a prompt to your embedder?

### ISSUE THREAD

**Issue by exploringweirdmachines** [dleemiller/WordLlama#46]
I mean. can you provide the special prompt tokens, like a special spice added to the text, before the text is going to be embedded together with it? Haha. Might get to influence the output embedding.

**Comment by dleemiller** [comment]
I'm not sure that it would help with a static embedding like this. Since wordllama is just using a set of token embeddings, adding a prompt would just "dilute" the average pooling from the rest of the tokens. I don't think it would be able to utilize it in the same way that a transformer model can.
